/**
 * InfoPanel class definition; wrapper around all info displayed in character and scene info popover
 */

const FILM_NAMES = [ 'The Fellowship of the Ring', 'The Two Towers', 'The Return of the King'];

// Tolkien Gateway URLs keyed by character name
const CHARACTER_WIKI_URLS = {
    'Frodo': 'https://tolkiengateway.net/wiki/Frodo_Baggins',
    'Sam': 'https://tolkiengateway.net/wiki/Samwise_Gamgee',
    'Merry': 'https://tolkiengateway.net/wiki/Meriadoc_Brandybuck',
    'Pippin': 'https://tolkiengateway.net/wiki/Peregrin_Took',
    'Gandalf': 'https://tolkiengateway.net/wiki/Gandalf',
    'Aragorn': 'https://tolkiengateway.net/wiki/Aragorn',
    'Legolas': 'https://tolkiengateway.net/wiki/Legolas',
    'Gimli': 'https://tolkiengateway.net/wiki/Gimli',
    'Boromir': 'https://tolkiengateway.net/wiki/Boromir',
};

// Brief character descriptions -- generated by Gemini
const CHARACTER_DESCRIPTIONS = {
    'Frodo': "A gentle Hobbit of the Shire burdened with the monumental task of carrying the One Ring to Mount Doom. Despite his small stature, he possesses immense inner strength and resilience against the Ring's corrupting influence.",
    'Sam': "Frodo's fiercely loyal gardener and closest friend, whose steadfast devotion keeps the quest alive during its darkest moments. He represents the everyday courage and pure heart needed to triumph over overwhelming evil.",
    'Merry': "A highly intelligent and resourceful Hobbit who frequently demonstrates tactical awareness and bravery far beyond his size. He matures into a valiant warrior, eventually playing a crucial role in the survival of Rohan.",
    'Pippin': "The youngest and most impulsive of the Hobbits, whose boundless curiosity often gets the group into trouble. However, he grows significantly throughout the journey, eventually proving his mettle as a courageous Guard of the Citadel in Gondor.",
    'Gandalf': "A wise, immensely powerful Wizard who serves as the guiding force and strategic mastermind behind the Fellowship. He sacrifices himself to save the others, later returning with even greater power to lead the free peoples against Sauron.",
    'Aragorn': "The hidden heir to the throne of Gondor, initially introduced as a rugged Ranger of the North named Strider. He is a master swordsman and a natural leader who must overcome his self-doubt to embrace his royal destiny.",
    'Legolas': "A sharp-eyed Elven prince from Mirkwood, renowned for his unmatched skill with a bow and his seemingly effortless agility in combat. Over the course of the journey, he forms an unlikely but profound friendship with the Dwarf Gimli.",
    'Gimli': "A proud, formidable Dwarf warrior who wields a battleaxe and possesses unwavering loyalty to his companions. Despite his gruff and stubborn exterior, he has a deep capacity for awe, honor, and enduring friendship.",
    'Boromir': "A valiant, fiercely protective captain of Gondor who joins the Fellowship desperate to find a weapon to save his beleaguered homeland. Though he tragically succumbs to the Ring's temptation, he redeems himself by dying heroically to defend Merry and Pippin."
};

const EXPAND_HINT = `<button class="expand-hint" aria-label="Expand panel for more detail">&#x26F6;&ensp;Expand for more detail</button>`;


class InfoPanel {

    /**
     * @param {Object} config - characterStats and sceneStats lookup maps
     * @param {Array}  data - parsed CSV rows
     */
    constructor(_config, _data) {
        this.data = _data;
        this.characterStats = _config.characterStats;
        this.sceneStats = _config.sceneStats;
        this.characterData = _config.characterData;
        this.corpusWordFreq  = _config.corpusWordFreq;
        this.corpusNgramFreq = _config.corpusNgramFreq;
        this.SCENE_INDEX = _config.SCENE_INDEX;
        this.isExpanded = false;
        this.initVis();
    }

    /**
     * Binds DOM element references and wires panel interaction event listeners
     */
    initVis() {
        this.panel     = document.getElementById('infoPanel');
        this.backdrop  = document.getElementById('infoPanelBackdrop');
        this.expandBtn = document.getElementById('expandInfoBtn');
        this.titleEl   = document.querySelector('#infoPanel .panel-title');
        this.contentEl = document.querySelector('#infoPanel .info-content');

        this.expandBtn.addEventListener('click', () => this.setExpanded(!this.isExpanded));
        this.backdrop.addEventListener('click', () => this.setExpanded(false));

        // Delegate expand-hint clicks so re-rendered content is always covered
        this.panel.addEventListener('click', e => {
            if (e.target.closest('.expand-hint')) this.setExpanded(true);
        });
    }

    /**
     * Toggles the panel between its default and expanded (centered overlay) states
     * @param {boolean} expand
     */
    setExpanded(expand) {
        this.isExpanded = expand;
        this.panel.classList.toggle('expanded', expand);
        this.backdrop.classList.toggle('visible', expand);
        this.expandBtn.innerHTML = expand ? '&#x2715;' : '&#x26F6;';
        this.expandBtn.setAttribute('aria-label', expand ? 'Collapse' : 'Expand');
        // Sync chart heights once the panel reaches its final expanded width.
        if (expand && (this.wordsVis || this.sceneCharsVis)) {
            const sync = () => {
                if (this.wordsVis) this.wordsVis._syncScrollHeight();
                if (this.sceneCharsVis) this.sceneCharsVis._syncScrollHeight();
            };
            const onEnd = e => {
                if (e.propertyName !== 'width') return;
                this.panel.removeEventListener('transitionend', onEnd);
                sync();
            };
            this.panel.addEventListener('transitionend', onEnd);
            setTimeout(sync, 400);
        }
    }

    /**
     * Renders character portrait, wiki link, and stat labels for the given name
     * @param {string} name - character name
     */
    showCharacter(name) {
        const stats  = this.characterStats[name];
        const imgSrc = `data/images/${name.toLowerCase()}.png`;

        // Display Wiki links
        const wikiUrl = CHARACTER_WIKI_URLS[name];
        const wikiLinkHTML = wikiUrl
            ? `<a class="char-wiki-link" href="${wikiUrl}" target="_blank" rel="noopener">View ${name}'s Wiki Page ↗</a>`
            : '';

        // Display character description
        const description = CHARACTER_DESCRIPTIONS[name];
        const descriptionHTML = description 
            ? `
            <div class="extended-section description-section">
                <p class="character-description">${description}</p>
            </div>` 
            : '';

        const fmt = v => (v != null && v !== 0) ? v.toLocaleString() : '—';

        this.titleEl.textContent = name;
        this.contentEl.innerHTML = `
            <div class="char-info">
                <img class="char-portrait"
                     src="${imgSrc}"
                     alt="${name}"
                     onerror="this.style.display='none'">
                ${wikiLinkHTML}
                <div class="char-stats">
                    <div class="char-stat">
                        <span class="stat-label">Lines</span>
                        <span class="stat-value">${fmt(stats?.lines)}</span>
                    </div>
                    <div class="char-stat">
                        <span class="stat-label">Words</span>
                        <span class="stat-value">${fmt(stats?.words)}</span>
                    </div>
                    <div class="char-stat">
                        <span class="stat-label">Scenes</span>
                        <span class="stat-value">${fmt(stats?.sceneCount)}</span>
                    </div>
                </div>
                <div class="char-extended">
                    ${descriptionHTML}
                    <div class="extended-section presence-section is-open">
                        <div class="section-header">
                            <span class="section-title">Scene Presence</span>
                            <span class="presence-info-icon section-info-icon">&#x2139;</span>
                            <span class="section-caret"></span>
                        </div>
                        <div class="section-body">
                            <div class="char-presence-chart"></div>
                        </div>
                    </div>
                    <div class="extended-section phrases-section">
                        <div class="section-header">
                            <span class="section-title">Top Phrases</span>
                            <span class="presence-info-icon phrases-info-icon section-info-icon">&#x2139;</span>
                            <span class="section-caret"></span>
                        </div>
                        <div class="section-body">
                            <div class="char-phrases-chart">
                                <div class="phrases-controls">
                                    <select class="words-select phrases-film-select">
                                        <option value="all">All Films</option>
                                        <option value="The Fellowship of the Ring">The Fellowship of the Ring</option>
                                        <option value="The Two Towers">The Two Towers</option>
                                        <option value="The Return of the King">The Return of the King</option>
                                    </select>
                                </div>
                                <div class="phrases-bars"></div>
                            </div>
                        </div>
                    </div>
                    <div class="extended-section words-section">
                        <div class="section-header">
                            <span class="section-title">Top Words</span>
                            <span class="presence-info-icon words-info-icon section-info-icon">&#x2139;</span>
                            <span class="section-caret"></span>
                        </div>
                        <div class="section-body">
                            <div class="char-words-chart">
                                <div class="words-controls">
                                    <select class="words-select film-select">
                                        <option value="all">All Films</option>
                                        <option value="The Fellowship of the Ring">The Fellowship of the Ring</option>
                                        <option value="The Two Towers">The Two Towers</option>
                                        <option value="The Return of the King">The Return of the King</option>
                                    </select>
                                    <select class="words-select mode-select">
                                        <option value="freq">Most Used</option>
                                        <option value="rate">Most Frequent</option>
                                        <option value="unique">Most Unique</option>
                                    </select>
                                </div>
                                <div class="words-scroll-wrap">
                                    <div class="words-chart-scroll"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                ${EXPAND_HINT}
            </div>`;

        // Initialize the CharacterPresence object
        new CharacterPresence(
            { parentElement: this.contentEl.querySelector('.char-presence-chart') },
            this.characterData[name] || [],
            this.SCENE_INDEX
        );

        // Initialize phrase cloud
        const phrasesVis = new CharacterPhrases(
            { parentElement: this.contentEl.querySelector('.phrases-bars') },
            this.characterData[name] || [],
            this.corpusNgramFreq
        );
        this.contentEl.querySelector('.phrases-film-select').addEventListener('change', e => {
            phrasesVis.updateVis(e.target.value);
        });

        // Initialize top-words bar chart
        this.wordsVis = null;
        const wordsVis = new HorizontalBarChart(
            { parentElement: this.contentEl.querySelector('.words-chart-scroll'), dataMode: 'words' },
            this.characterData[name] || [],
            this.corpusWordFreq
        );
        this.wordsVis = wordsVis;

        // If panel already expanded, _syncScrollHeight can measure immediately
        if (this.isExpanded) requestAnimationFrame(() => wordsVis._syncScrollHeight());

        // Wire film and mode dropdowns
        this.contentEl.querySelector('.film-select').addEventListener('change', e => {
            wordsVis.updateVis(e.target.value, undefined);
        });
        this.contentEl.querySelector('.mode-select').addEventListener('change', e => {
            wordsVis.updateVis(undefined, e.target.value);
        });

        // Wire collapsible section headers (description-section has no header; skip it)
        this.contentEl.querySelectorAll('.extended-section').forEach(section => {
            const header = section.querySelector('.section-header');
            if (!header) return;

            header.addEventListener('click', () => {
                const opening = !section.classList.contains('is-open');
                section.classList.toggle('is-open');
                if (opening && section.classList.contains('words-section') && this.wordsVis) {
                    requestAnimationFrame(() => this.wordsVis._syncScrollHeight());
                }
            });
        });

        // Shared tooltip element
        const tooltip = document.getElementById('presence-tooltip');

        // Wire the words info icon
        const wordsIcon = this.contentEl.querySelector('.words-info-icon');
        if (wordsIcon && tooltip) {
            wordsIcon.addEventListener('mouseover', e => {
                tooltip.style.display = 'block';
                tooltip.style.left = (e.pageX + 10) + 'px';
                tooltip.style.top  = (e.pageY + 10) + 'px';
                tooltip.innerHTML  = '<span class="pt-name">About this chart</span>'
                    + 'Most frequent words from this character\'s dialogue after removing common filler words. '
                    + '<br><br><strong>Most Unique</strong> re-ranks by how distinctively this character uses each word: '
                    + 'character count ÷ (cast-wide count + 1). Higher scores mean the word is characteristic of this character specifically.';
            });
            wordsIcon.addEventListener('mousemove', e => {
                tooltip.style.left = (e.pageX + 10) + 'px';
                tooltip.style.top  = (e.pageY + 10) + 'px';
            });
            wordsIcon.addEventListener('mouseout', () => { tooltip.style.display = 'none'; });
        }

        // Wire the phrases info icon
        const phrasesIcon = this.contentEl.querySelector('.phrases-info-icon');
        if (phrasesIcon && tooltip) {
            phrasesIcon.addEventListener('mouseover', e => {
                tooltip.style.display = 'block';
                tooltip.style.left = (e.pageX + 10) + 'px';
                tooltip.style.top  = (e.pageY + 10) + 'px';
                tooltip.innerHTML  = '<span class="pt-name">About this chart</span>'
                    + 'Phrases this character repeats most — larger and brighter means said more often. '
                    + '<br><br><strong>All Films</strong> ranks by raw repetition count. '
                    + '<strong>Single film</strong> ranks by how exclusively this character says the phrase vs. the full cast. '
                    + 'Hover a phrase to see an example line.';
            });
            phrasesIcon.addEventListener('mousemove', e => {
                tooltip.style.left = (e.pageX + 10) + 'px';
                tooltip.style.top  = (e.pageY + 10) + 'px';
            });
            phrasesIcon.addEventListener('mouseout', () => { tooltip.style.display = 'none'; });
        }

        // Wire the presence info icon
        const infoIcon = this.contentEl.querySelector('.presence-info-icon:not(.words-info-icon):not(.phrases-info-icon)');
        if (infoIcon && tooltip) {
            infoIcon.addEventListener('mouseover', e => {
                tooltip.style.display = 'block';
                tooltip.style.left = (e.pageX + 10) + 'px';
                tooltip.style.top  = (e.pageY + 10) + 'px';
                tooltip.innerHTML  = '<span class="pt-name">About this chart</span>Reflects spoken dialogue only — not visual screen presence.';
            });
            infoIcon.addEventListener('mousemove', e => {
                tooltip.style.left = (e.pageX + 10) + 'px';
                tooltip.style.top  = (e.pageY + 10) + 'px';
            });
            infoIcon.addEventListener('mouseout', () => { tooltip.style.display = 'none'; });
        }
    }

    /**
     * Renders scene name, film, and stat labels for the scene at the given index
     * @param {number} index - 0–95
     */
    showScene(index) {
        const sceneName = SCENE_NAMES[index] ?? '';
        const stats     = this.sceneStats[sceneName];
        const filmName  = FILM_NAMES[Math.floor(index / 32)] ?? '';

        const fmt = v => (v != null && v !== 0) ? v.toLocaleString() : '—';

        this.titleEl.textContent = 'Scene Info';
        this.contentEl.innerHTML = `
            <div class="scene-info">
                <h3 class="scene-name">${sceneName}</h3>
                <p class="scene-film">${filmName}</p>
                <img class="scene-thumb" src="data/images/scenes/${index}.png" alt="${sceneName}">
                <div class="scene-stats">
                    <div class="char-stat">
                        <span class="stat-label">Lines</span>
                        <span class="stat-value">${fmt(stats?.lines)}</span>
                    </div>
                    <div class="char-stat">
                        <span class="stat-label">Characters</span>
                        <span class="stat-value">${fmt(stats?.characterCount)}</span>
                    </div>
                    <div class="char-stat">
                        <span class="stat-label">Fellowship</span>
                        <span class="stat-value">${stats?.fellowshipCount != null ? `${stats.fellowshipCount} / 9` : '— / 9'}</span>
                    </div>
                </div>
                <div class="scene-extended">
                    <div class="extended-section is-open">
                        <div class="section-header">
                            <span class="section-title">Speaking Characters</span>
                            <span class="section-caret"></span>
                        </div>
                        <div class="section-body">
                            <div class="scene-chars-chart">
                                <div class="words-scroll-wrap">
                                    <div class="scene-chars-scroll"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="extended-section">
                        <div class="section-header">
                            <span class="section-title">Scene Script</span>
                            <span class="section-caret"></span>
                        </div>
                        <div class="section-body scene-script-body">
                            <div class="scene-transcript"></div>
                        </div>
                    </div>
                </div>
                ${EXPAND_HINT}
            </div>`;

        // Speaking characters bar chart
        const sceneRows = this.data.filter(r => r.scene_name === sceneName);

        this.sceneCharsVis = new HorizontalBarChart(
            {
                parentElement: this.contentEl.querySelector('.scene-chars-scroll'),
                dataMode: 'lines',
                colorFn: d => characterColor(d.word, 0.9),
                maxRows: 6,
                rowHeight: 16,
            },
            sceneRows,
            null
        );

        // Scene transcript visualization

        // Merge consecutive rows from the same speaker into one screenplay block
        const beats = [];
        sceneRows.forEach(r => {
            if (beats.length && beats[beats.length - 1].character === r.character) {
                beats[beats.length - 1].lines.push(r.dialogue);
            } else {
                beats.push({ character: r.character, lines: [r.dialogue] });
            }
        });

        // Place in panel
        const transcript = this.contentEl.querySelector('.scene-transcript');
        beats.forEach(beat => {
            const div = document.createElement('div');
            div.className = 'transcript-entry';
            div.style.setProperty('--char-color', characterColor(beat.character, 0.9));
            div.innerHTML = `
                <span class="transcript-character">${beat.character}</span>
                <div class="transcript-lines">
                    ${beat.lines.map(l => `<p class="transcript-dialogue">${l}</p>`).join('')}
                </div>`;
            transcript.appendChild(div);
        });

        // Wire collapsible section headers and re-sync chart height when chars section re-opens
        this.contentEl.querySelectorAll('.scene-extended .extended-section').forEach(section => {
            section.querySelector('.section-header')?.addEventListener('click', () => {
                const opening = !section.classList.contains('is-open');
                section.classList.toggle('is-open');
                if (opening && this.sceneCharsVis) {
                    requestAnimationFrame(() => this.sceneCharsVis._syncScrollHeight());
                }
            });
        });
    }
}
